@host = https://localhost:7181
@username = operator01
@password = StrongP@ssw0rd123
@email = operator01@example.com
@phone = +48111111111
@inn = 123456789012
@address = Warsaw Center 10
@cityId = 1
@code = 123456
@destPhone = +48222222222
@csrf = replace-me

### CSRF token
GET {{host}}/auth/csrf
Accept: application/json

###

POST {{host}}/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}",
  "phoneNumber": "{{phone}}",
  "inn": "{{inn}}",
  "address": "{{address}}",
  "cityId": {{cityId}}
}

###

POST {{host}}/auth/request-confirmation
Content-Type: application/json

{}

###

POST {{host}}/auth/confirm-email
Content-Type: application/json

{
  "code": "{{code}}"
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

GET {{host}}/auth/profile
Accept: application/json

###

GET {{host}}/calls/cities
Accept: application/json

###

GET {{host}}/calls/active
Accept: application/json

###

POST {{host}}/calls/start
Content-Type: application/json
X-CSRF-TOKEN: {{csrf}}

{
  "destPhone": "{{destPhone}}"
}

###

POST {{host}}/calls/end
Content-Type: application/json
X-CSRF-TOKEN: {{csrf}}

{
  "destPhone": "{{destPhone}}"
}

###

POST {{host}}/auth/logout
Content-Type: application/json
X-CSRF-TOKEN: {{csrf}}

{}
