@TelephoneCallRecording_HostAddress = http://localhost:5070

@username = testuser3
@password = StrongP@ssw0rd123
@email = test3@example.com
@code = 472569


### Auth test

GET {{TelephoneCallRecording_HostAddress}}/auth/profile
Accept: application/json

###

POST {{TelephoneCallRecording_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}"
}

###

POST {{TelephoneCallRecording_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST {{TelephoneCallRecording_HostAddress}}/auth/confirm-email
Content-Type: application/json

{
  "username": "{{username}}",
  "code": "{{code}}"
}

###

GET {{TelephoneCallRecording_HostAddress}}/auth/profile
Accept: application/json

###

POST {{TelephoneCallRecording_HostAddress}}/auth/logout

###

### Wrong Auth test

POST {{TelephoneCallRecording_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "wrong_password"
}

###

POST {{TelephoneCallRecording_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}"
}

###