// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelephoneCallRecording.Services.DataBase.Authorization;

#nullable disable

namespace TelephoneCallRecording.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419131645_AddUserRole#1")]
    partial class AddUserRole1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelephoneCallRecording.Models.Authorization.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmationCodeHash")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("email_confirmation_code_hash");

                    b.Property<DateTime?>("EmailConfirmationExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmation_expires");

                    b.Property<int>("FailedEmailConfirmAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_email_confirm_attempts");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_confirmed");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Client")
                        .HasColumnName("role");

                    b.Property<int?>("SubscriberId")
                        .HasColumnType("integer")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubscriberId")
                        .IsUnique()
                        .HasFilter("\"subscriber_id\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.CallRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("call_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("DestPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dest_phone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<long>("StartUnixTime")
                        .HasColumnType("bigint")
                        .HasColumnName("start_unix_time");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("integer")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("time_of_day");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("SubscriberId", "DestPhone");

                    b.HasIndex("SubscriberId", "DestPhone", "DurationMinutes")
                        .IsUnique()
                        .HasFilter("\"duration_minutes\" IS NULL");

                    b.ToTable("calls", (string)null);
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DayTariff")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("day_tariff");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NightTariff")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("night_tariff");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.CityDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("city_discount_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<int?>("MaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_minutes");

                    b.Property<int>("MinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("min_minutes");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "MinMinutes")
                        .IsUnique();

                    b.ToTable("city_discounts", (string)null);
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subscriber_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("subscribers", (string)null);
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Authorization.User", b =>
                {
                    b.HasOne("TelephoneCallRecording.Models.Calls.Subscriber", "Subscriber")
                        .WithOne("User")
                        .HasForeignKey("TelephoneCallRecording.Models.Authorization.User", "SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.CallRecord", b =>
                {
                    b.HasOne("TelephoneCallRecording.Models.Calls.City", "City")
                        .WithMany("Calls")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelephoneCallRecording.Models.Calls.Subscriber", "Subscriber")
                        .WithMany("Calls")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.CityDiscount", b =>
                {
                    b.HasOne("TelephoneCallRecording.Models.Calls.City", "City")
                        .WithMany("Discounts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.Subscriber", b =>
                {
                    b.HasOne("TelephoneCallRecording.Models.Calls.City", "City")
                        .WithMany("Subscribers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.City", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("Discounts");

                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("TelephoneCallRecording.Models.Calls.Subscriber", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
